### ISSUE TITLE
error on creating account

### ISSUE THREAD

**Issue by murdocmurat** [poszer/FusionCMS#1]
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0 = 1' at line 1

UPDATE `account` SET 0 = 1

Filename: C:/xampp/htdocs/system/database/DB_driver.php

Line Number: 656

bnetaccounts u need to edit yourself than u can login into game it will not auto adding the agrements

**Comment by ELdoBA** [comment]
Can't reproduce issue. Just installed without any error.
Check your config files
