### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by Ps3mk18** [poszer/FusionCMS#13]
**Describe the bug**

**To Reproduce**
1. Go to 'Installer'
2. Do all steps until installation shoud Writing configs
3. Installer stucks @ Writing configs...
4. Nothing happens. No database entries after 15 minutes.

![Bild_2021-06-23_155040](https://user-images.githubusercontent.com/50773978/123108475-c26c4800-d43a-11eb-8cf0-f0840aa97a36.png)

**Comment by ELdoBA** [comment]
Make sure you have entered correct details for database (name, user, pw). I can't reproduce this error.
