### ISSUE TITLE
Forum en realm status error

### ISSUE THREAD

**Issue by stijndioos** [poszer/FusionCMS#5]
Hi there first of all thanks for the nice cms! 

but unfortunately i can't open the forum. 
I get the following error.

Something went wrong!

Technical data:
Fatal error: Cannot declare class Error, because the name is already in use in C:\xampp\htdocs\application\modules\error\controllers\error.php on line 3

And sometimes at realm status I also get the following error

A PHP Error was encountered
Severity: Warning

Message: count(): Parameter must be an array or an object that implements Countable

Filename: libraries/realms.php

Line Number: 201

Do you have a solution for this? Greetings Stijn

**Comment by ELdoBA** [comment]
Hi @stijndioos  and thanks. Forum isn't implemented as default yet (I can't promise, but we might do a forum module soon) also as the alternative, you can use IPB 4 and make bridge. 
For the other error in libraries/realms.php at line 201, i don't see anything wrong there. Which version of PHP you using? If you are on 7.2, It may be an issue with that version.

**Comment by stijndioos** [comment]
Hi in advance thanks for the quick response! The error has disappeared in the realms module.
I have  [if (! count ($ this-> hordeRaces))]
changed to [if (! count ((array) $ this-> hordeRaces))]

And the forum section temporarily deleted.

But I now have the following problem with the armory part. The stats issue in worldserver.conf
I adjusted but the talents part does not work as it should. you cannot see which tallents players have set. everything else works from stats etc.
any idea what that could be? have searched the entire internet without result.
Below you will find an example image of the talents section
 Thanks already! Greetings Stijn
![Naamloos-1](https://user-images.githubusercontent.com/61931689/76265749-b9675f80-6265-11ea-9921-7e2bd81ebda2.jpg)

**Comment by ELdoBA** [comment]
> Hi in advance thanks for the quick response! The error has disappeared in the realms module.
> I have [if (! count ($ this-> hordeRaces))]
> changed to [if (! count ((array) $ this-> hordeRaces))]
> 
> And the forum section temporarily deleted.
> 
> But I now have the following problem with the armory part. The stats issue in worldserver.conf
> I adjusted but the talents part does not work as it should. you cannot see which tallents players have set. everything else works from stats etc.
> any idea what that could be? have searched the entire internet without result.
> Below you will find an example image of the talents section
> Thanks already! Greetings Stijn
> ![Naamloos-1](https://user-images.githubusercontent.com/61931689/76265749-b9675f80-6265-11ea-9921-7e2bd81ebda2.jpg)

Give me some minutes, i'll setup clean version and test that part

**Comment by ELdoBA** [comment]
Tested on clean build, i can't reproduce any problem with talents tab. 
Image below: 
![Screenshot_1](https://user-images.githubusercontent.com/41213210/76317932-3da8f980-62dd-11ea-88a5-fd2d54d09c95.png)

I have updated the Readme file with the requirements. Please, read them and try to setup following it, it should work without problems. 
https://github.com/poszer/FusionCMS/blob/master/README.md
